### PR TITLE
CHNAGE IS YES

### PR DESCRIPTION
**Pull request by moon1789**
i change the everythin

### CODE REVIEW

**Comment by mobilegmYT** [comment]
I will have a look, BTW @moon1789 can you fix the merge conflict?

**Comment by F-fengzi** [comment]
we should use a new branch if you want to have a look

**Comment by mobilegmYT** [comment]
> we should use a new branch if you want to have a look

So I've had a look, the website is pretty broken so not sure a full merge would work, but maybe coping some cool elements to a dev branch would work better.

**Comment by F-fengzi** [comment]
> > we should use a new branch if you want to have a look
> 
> So I've had a look, the website is pretty broken so not sure a full merge would work, but maybe coping some cool elements to a dev branch would work better.

what elements do you think is cool to add?

**Comment by moon1789** [comment]
> I will have a look, BTW @moon1789 can you fix the merge conflict?

well
might think so

**Comment by moon1789** [comment]
what problems tho

**Comment by moon1789** [comment]
index
humm leme check

**Comment by mobilegmYT** [comment]
> > > we should use a new branch if you want to have a look
> > 
> > 
> > So I've had a look, the website is pretty broken so not sure a full merge would work, but maybe coping some cool elements to a dev branch would work better.
> 
> what elements do you think is cool to add?

Well this more simplified home page looks good, maybe we could change the buttons currently to be a bit smaller and squeeze the "learn more" button in there to redirect to about.html, and move the join our discord button to the footer or header.
image

**Comment by moon1789** [comment]
yea , sounds good

**Comment by F-fengzi** [comment]
well, 
1. the about page is mostly credits, so a "learn more" button to there is not quite accurate
2. people can easily navigate by the top bar, which is even optimized for mobile
3. if you really want to add the feature, the original codebase is easier to update. instead of merging this whole new one which is very disordered

**Comment by mobilegmYT** [comment]
> well,
> 
> 1. the about page is mostly credits, so a "learn more" button to there is not quite accurate
> 2. people can easily navigate by the top bar, which is even optimized for mobile
> 3. if you really want to add the feature, the original codebase is easier to update. instead of merging this whole new one which is very disordered

Yea true, maybe we could just close this and either change the about page to have info about the OS itself, or just put os info below the home page.

**Comment by F-fengzi** [comment]
let's continue this thread in discord lmao, github is not a messaging app

**Pull request closed without merging**
